<a href="https://colab.research.google.com/github/jakubtwalczak/dsbootcampudemy/blob/main/3_Funkcje_statystyczne_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Temat był już poruszony w pierwszym notebooku, teraz pora na jego rozwinięcie.

In [1]:
import numpy as np

Zacznijmy od utworzenia tablicy zawierającej fikcyjne dane dot. notowań giełdowych spółki z trzech dni (kolejno cena otwarcia, najwyższa, najniższa, zamknięcia i wolumen akcji).

In [3]:
price = np.array([[99.30, 102.15, 97.80, 101.80, 6500],
          [101.80, 103.10, 100.20, 100.90, 4200],
          [100.90, 101.50, 98.75, 100.45, 3800]])

price

array([[  99.3 ,  102.15,   97.8 ,  101.8 , 6500.  ],
       [ 101.8 ,  103.1 ,  100.2 ,  100.9 , 4200.  ],
       [ 100.9 ,  101.5 ,   98.75,  100.45, 3800.  ]])

In [4]:
price.shape

(3, 5)

# Sum.

Jeżeli użyjemy funkcję **sum**, uzyskujemy jedną wartość - sumę wszystkich elementów tablicy.

In [5]:
np.sum(price)

15708.65

Jeżeli chcemy policzyć sumę w każdej kolumnie lub każdym wierszu, musimy podać funkcji parametr osi - axis (0 - kolumna, 1 - wiersz).

In [6]:
print(np.sum(price, axis=0))
print(np.sum(price, axis=1))

[  302.     306.75   296.75   303.15 14500.  ]
[6901.05 4606.   4201.6 ]


# Min, Max, Mean, Std, Var, Median.

Pozostałe funkcje statystyczne: **Min**, **Max**, **Mean**, **Median**, **Std**, **Var** stosuje się w podobny sposób.

In [7]:
print(np.min(price))
print(np.min(price, axis=0))
print(np.min(price, axis=1))

97.8
[  99.3   101.5    97.8   100.45 3800.  ]
[ 97.8  100.2   98.75]


In [8]:
print(np.max(price))
print(np.max(price, axis=0))
print(np.max(price, axis=1))

6500.0
[ 101.8  103.1  100.2  101.8 6500. ]
[6500. 4200. 3800.]


In [9]:
print(np.mean(price))
print(np.mean(price, axis=0))
print(np.mean(price, axis=1))

1047.2433333333333
[ 100.66666667  102.25         98.91666667  101.05       4833.33333333]
[1380.21  921.2   840.32]


In [10]:
print(np.std(price))
print(np.std(price, axis=0))
print(np.std(price, axis=1))

1966.4008192521571
[1.03387083e+00 6.57013445e-01 9.86858090e-01 5.61248608e-01
 1.18977122e+03]
[2559.89550459 1639.40028669 1479.8402828 ]


In [11]:
print(np.var(price))
print(np.var(price, axis=0))
print(np.var(price, axis=1))

3866732.181955555
[1.06888889e+00 4.31666667e-01 9.73888889e-01 3.15000000e-01
 1.41555556e+06]
[6553064.9944 2687633.3    2189927.2626]


In [12]:
print(np.median(price))
print(np.median(price, axis=0))
print(np.median(price, axis=1))

101.5
[ 100.9   102.15   98.75  100.9  4200.  ]
[101.8 101.8 100.9]
